kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: file-beat-es-secret
  namespace: monitoring  # Default namespace, can be overridden by deploy.sh
stringData:
  ELASTICSEARCH_USERNAME: elastic
  ELASTICSEARCH_PASSWORD: $(oc get secret elasticsearch-sample-es-elastic-user -n openshift-operators -o=jsonpath='{.data.elastic}' | base64 --decode)