# Filebeat configuration for collecting container logs
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  namespace: eck-demo
spec:
  type: filebeat
  version: 8.17.0
  elasticsearchRef:
    name: elasticsearch-sample
    namespace: openshift-operators
  config:
    filebeat:
      autodiscover:
        providers:
        - hints:
            default_config:
              paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log
              type: container
            enabled: true
          node: ${NODE_NAME}
          type: kubernetes
    processors:
    - add_kubernetes_metadata:
        host: ${NODE_NAME}
        matchers:
        - logs_path:
            logs_path: /var/log/containers/
    - decode_json_fields:
        add_error_key: true
        fields:
        - message
        overwrite_keys: true
        target: ""
    - drop_fields:
        fields:
        - ecs
        - input
        - agent
        ignore_missing: true
    logging.json: true
    logging.level: debug
  daemonSet:
    podTemplate:
      spec:
        serviceAccount: filebeat
        automountServiceAccountToken: true
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        containers:
        - name: filebeat
          securityContext:
            privileged: true
            runAsUser: 0
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          resources:
            limits:
              memory: 200Mi
              cpu: 500m
            requests:
              memory: 100Mi
              cpu: 100m
          volumeMounts:
          - mountPath: /var/log/containers
            name: varlogcontainers
          - mountPath: /var/log/pods
            name: varlogpods
          - mountPath: /var/lib/docker/containers
            name: varlibdockercontainers
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
