# Filebeat configuration for collecting container logs
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  namespace: eck-demo
spec:
  type: filebeat
  version: 8.17.0
  elasticsearchRef:
    name: elasticsearch-sample
    namespace: openshift-operators
  config:
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
                - logs_path:
                    logs_path: /var/log/containers/
          - dissect:
              field: "log.file.path"
              pattern: "/var/log/containers/%{pod.name}_%{kubernetes.namespace}_%{container.name}-%{container.id}.log"
              ignore_failure: true
          - drop_fields:
              fields: ["pod.name"]
              ignore_missing: true
          - rename:
              fields:
                - from: "container.name"
                  to: "kubernetes.container.name"
              ignore_missing: true
          - decode_json_fields:
              fields: ["message"]
              target: ""
              overwrite_keys: true
    processors:
      - add_host_metadata: ~
      - add_cloud_metadata: ~
      - add_docker_metadata: ~
    logging.json: true
    logging.level: debug
  daemonSet:
    podTemplate:
      spec:
        serviceAccount: filebeat
        automountServiceAccountToken: true
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
          resources:
            limits:
              memory: 200Mi
              cpu: 500m
            requests:
              memory: 100Mi
              cpu: 100m
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
