# Filebeat DaemonSet configuration for container log collection
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  namespace: monitoring  # Default namespace, can be overridden by deploy.sh
spec:
  type: filebeat
  version: 8.17.0
  elasticsearchRef:
    name: elasticsearch-sample
    namespace: monitoring  # Must match Elasticsearch namespace
  kibanaRef:
    name: kibana-sample
    namespace: monitoring  # Must match Kibana namespace
  config:
    filebeat:
      # inputs:
      #   - type: container
      #     paths:
      #       - /var/log/containers/*.log
      autodiscover:
        providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints:
            enabled: true
            default_config:
              type: container
              paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log
    processors:
    # - add_cloud_metadata: {}
    # - add_host_metadata: {}
    - add_kubernetes_metadata:
          deployment: true
          namespace: true
    - drop_event:
        when:
          not:
            equals:
              kubernetes.container.name: log-generator
    # - decode_json_fields:
    #     fields: ["message"]
    #     target: ""
    #     overwrite_keys: true
    # - drop_fields:
    #     fields: ["ecs", "input", "agent"]
    #     ignore_missing: true
    logging.json: true
    logging.level: debug
  # secureSettings:
  # - secretName: file-beat-es-secret
  daemonSet:
    podTemplate:
      spec:
        serviceAccount: filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        containers:
        - name: filebeat
          securityContext:
            privileged: true
            runAsUser: 0
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          resources:
            limits:
              memory: 200Mi
              cpu: 500m
            requests:
              memory: 100Mi
              cpu: 100m
          volumeMounts:
          - mountPath: /var/log/containers
            name: varlogcontainers
          - mountPath: /var/log/pods
            name: varlogpods
          - mountPath: /var/lib/docker/containers
            name: varlibdockercontainers
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
