# RBAC configuration for Filebeat
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: monitoring  # Default namespace, can be overridden by deploy.sh
  labels:
    beat.k8s.elastic.co/name: filebeat
---
# Cluster-level permissions for pod metadata access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-cluster-role
  namespace: monitoring  # Default namespace, can be overridden by deploy.sh
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
---
# Bind the ClusterRole to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: monitoring  # Default namespace, can be overridden by deploy.sh
roleRef:
  kind: ClusterRole
  name: filebeat-cluster-role
  apiGroup: rbac.authorization.k8s.io
