# This sample sets up an Elasticsearch cluster with an OpenShift route
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
  namespace: monitoring
spec:
  version: 8.17.4
  nodeSets:
  - name: default
    count: 2
    config:
      node.store.allow_mmap: false
      xpack.security.http.ssl.verification_mode: none
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_USERNAME
            value: "elastic"
          - name: ES_PASSWORD
            value: "7BJw1354965hcSWiaXP0n6FR"
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
