# Elasticsearch cluster configuration for ECK (Elastic Cloud on Kubernetes)
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
  namespace: openshift-operators
spec:
  version: 8.17.0
  nodeSets:
  - name: default
    count: 3
    config:
      node.roles:
      - master
      - data
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          foo: bar
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 4Gi
