apiVersion: v1
kind: ConfigMap
metadata:
  name: my-index-configmap
  namespace: monitoring
data:
  index-definition.json: |
    {
      "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 1
      },
      "mappings": {
        "properties": {
          "field1": {
            "type": "keyword"
          },
          "field2": {
            "type": "text"
          }
        }
      }
    }

