# Kibana dashboard configuration for ECK
# This configures a single Kibana instance connected to Elasticsearch
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
  namespace: openshift-operators
spec:
  version: 8.17.0
  count: 1
  elasticsearchRef:
    name: elasticsearch-sample
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2Gi
            cpu: 2
