# Kibana configuration with Elasticsearch integration
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
  namespace: monitoring  # Default namespace, can be overridden by deploy.sh
spec:
  version: 8.17.0
  count: 1
  elasticsearchRef:
    name: elasticsearch-sample
    namespace: monitoring  # Must match Elasticsearch namespace
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 1
          limits:
            memory: 1Gi
            cpu: 1
